### ISSUE TITLE
Wrong entity appearance

### ISSUE THREAD

**Issue by Ametis81** [WolvenKit/Cyberpunk-Blender-add-on#100]
Some entities have wrong appearance after importing them in Blender via entity import or sector import

How to reproduce:
1. Import `common_lift.ent.json` with appearance `neomilitary_a_hotel_1_door`

In game:
![image1](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/117985431/9265c2d7-facd-472c-abbe-f1ac8cd89ff0)

In Blender:
![image2](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/117985431/6bb47aff-7f1e-4f0d-8e40-b217c1d88748)

2, Import `activated_distraction_air_conditioner.ent.json` with appearance `air_conditioner_roof`

In game:
![image3](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/117985431/0bd784e5-3f3c-4823-bc1c-bff9ba8c2266)

In Blender:
![image4](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/117985431/3a8ebb11-dedd-415e-9306-8104c612516e)

**Comment by Simarilius-uk** [comment]
fixed in 66920e4
