### ISSUE TITLE
AKL Autofitter wrong outputs on Blender 4.02

### ISSUE THREAD

**Issue by thaneize** [WolvenKit/Cyberpunk-Blender-add-on#101]
Tested with Blender v4.02 and Cyberpunk Add On v1.52. Used a vanilla game file exported to GITF with Wolvenkit v8.11.0.

The AKL Autofitter refits to the wrong lattice modifier.

It either puts out a different preset (Hyst EBBP is exported as Solo Arms), applies no deformation at all (Flat Chest, doesn't even connect itself with the Mesh), or it delivers the wrong deformation (Hyst EEB RB for example)

![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/154638686/8f9d2457-d687-4088-a4e5-ef4a518d62e7)

![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/154638686/53546dc4-fa21-4f45-8da1-88df142b6135)

**Comment by DoctorPresto** [comment]
resolved
