### ISSUE TITLE
feature request: Switch armature body gender

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#105]
It would be awesome if I could have a button that will parent the current selection to an armature of the other body gender under consideration of the bone offsets (maybe with automatic weights or so?). I'm still doing it manually and it's annoying.

If the feature already exists, tell me and I'll try to update the docs :)

**Comment by manavortex** [comment]
2, and maybe add a convenience function to parent and re-weight...? There are workflows for that, maybe the Netrunner suit could be used (provided as default parenting target)?

**Comment by DoctorPresto** [comment]
Pretty sure I can store the weights from the netrunner suit in an array and apply them, I'll take a look at this later this week and ping you for some testing. Option 2 is no issue at all, ill try to get this changed tonight.

**Comment by manavortex** [comment]
solved via "load bundled rigs" :)
