### ISSUE TITLE
Imported skeleton has no hierarchy and bone rotation axes

### ISSUE THREAD

**Issue by Tosyk** [WolvenKit/Cyberpunk-Blender-add-on#107]
Imported skeleton has no hierarchy and bone rotation axes.

![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/24209966/94d0a0a2-1050-4699-88ff-97745b99ddfc)

here's the example of proper bone rotation axes:
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/24209966/feeda478-8ff4-42b7-976e-0f352bccb8b5)

Is it possible to add both?

**Comment by DoctorPresto** [comment]
The bones that import with a mesh by default are just empty objects created because there are named vertex groups. If you want an actual rig, either use a withrig export from wkit or use one of the rigs which are bundled with the plugin
