### ISSUE TITLE
Vehicle animations broken

### ISSUE THREAD

**Issue by misterchedda** [WolvenKit/Cyberpunk-Blender-add-on#123]
Importing/exporting vehicle .anims file without any edits in Blender breaks vehicle animations completely

### Versions
- Blender add-on: 1.5.3 (and tested on [this ](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/actions/runs/8223434624)more recent build too)
- Wolvenkit 8.13.0

### Repro steps:
- Add and export `base\animations\vehicle\sport\vehicle\v_sport1_rayfield_caliburn.anims` from an empty Wkit project
- Import glb to Blender
- Make no edits and export to glb as "Animations"
- Import to Wkit with Target file format = "Anims"
- Vehicle animations should be broken like below with all rigged parts centered around the origin:
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/158098195/603f8ff6-3912-4146-92dd-7830af08bfca)

**Comment by misterchedda** [comment]
if helpful, happy to provide the .glb files before/after export/import at each step

**Comment by DoctorPresto** [comment]
This is not a blender issue, vehicle anims are additives and there is a math issue on the Wolvenkit side at the moment. Other additive animations lead to much worse results though, at least we can see your car :D

**Comment by misterchedda** [comment]
Oh so it IS related to the TPP bike anim I reported a month ago. Thanks! I guess Ill close the issue then

**Comment by DoctorPresto** [comment]
Yeah, absolutely :D

If you watch the Wolvenkit log as you're exporting, it'll tell you if the anims you're wanting to edit are additives, if they are, you won't be able to import them properly

**Comment by Simarilius-uk** [comment]
fixed my effs commit.
