### ISSUE TITLE
UnboundLocalError: cannot access local variable 'MaskTexture' where it is not associated with a value

### ISSUE THREAD

**Issue by Surasia** [WolvenKit/Cyberpunk-Blender-add-on#130]
While importing lizzy wizzy's ep1 (phantom liberty) model ENT, some mask textures fail to import with this error in the console:

```
UnboundLocalError: cannot access local variable 'MaskTexture' where it is not associated with a value
None
Mask image not found for layer  1
Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\importers\import_with_materials.py", line 167, in CP77GLBimport
    bpymat = Builder.create(index)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\main\setup.py", line 61, in create
    multilayered.create(rawMat["Data"],bpyMat)
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 664, in create
    self.createLayerMaterial(os.path.basename(Data["MultilayerSetup"])[:-8]+"_Layer_",LayerCount,CurMat,Data["MultilayerMask"],LayerNormal)
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 192, in createLayerMaterial
    MaskN = create_node(CurMat.nodes,"ShaderNodeTexImage",(-2400,400-100*x), image = MaskTexture,label="Layer_"+str(x+1))
                                                                                     ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'MaskTexture' where it is not associated with a value
```

I'm using Blender 4.2 Alpha, with Wolvenkit 8.13.0-nightly.2024-04-01 and the latest release version of the addon.

**Comment by Simarilius-uk** [comment]
your masks havent been written by wkit to the depot for some reason. Someone had this the other day and used a new folder for their depot in wkit and reran the export and it worked ok. try that.

**Comment by DoctorPresto** [comment]
Also please note that you won't be able to import any meshes back into Wolvenkit with anything past blender 4.02. I'd really recommend against using alpha builds of blender (or even beta builds) as there are often API changes which will require the rest of the tool chain to be updated. 4.2 isn't scheduled to release until mid July.

**Comment by Surasia** [comment]
Hm, the issue seems to persist even after moving/emptying the depot, re-exporting a few times and redoing the project. I'll try an earlier version of Blender- I appreciate the heads up on the blender versions. Had me wondering why my imports weren't working :D Will report back with 4.0.2 in a moment.

**Comment by Surasia** [comment]
Yep, same issue with older versions of Blender and Wolvenkit. I'll close the issue for now as it is highly likely I have something misconfigured, or that it is an issue with Wolvenkit not reading files properly. Before the openJSON changes the imports would be wrongly misconfigured as well, but now there are also tracebacks. The issues started around when I updated the game to 2.1, so I'll try everything in a completely clean environment (VM) with a new install.

**Comment by DoctorPresto** [comment]
Just want to be sure as this is a common misunderstanding I've ran into. You changed the depot path that you have set in wolvenkit - tools - settings and then re exported everything and the error persisted? 

Can you confirm you have done the above and not just removed files from the project?

Can you also confirm that you did _not_ change the depot path in the blender plugin preferences?

**Comment by Surasia** [comment]
Yep, I made sure to check the depot path, re-export with the new depot settings, wiped the depot, not the project. Same textures, with the same issue.

**Comment by Surasia** [comment]
With the latest uploaded build (through github actions) and Wolvenkit 8.13.0-nightly.2024-04-21, everything seems to work! All models import properly.
