### ISSUE TITLE
Combine materials for decal meshes that use the same material

### ISSUE THREAD

**Issue by Holopointz** [WolvenKit/Cyberpunk-Blender-add-on#156]
Instead of having a new material for every decal mesh such as "decal_material.414, decal_material.415, decal_material.416", let decal meshes share the same material when they are the same. 

Could potentially remove hundreds of duplicate materials from sector imports and make editing them easier, any changes to "dust_patch_01" for example would also apply to all the other decal meshes that use that material.

**Comment by Simarilius-uk** [comment]
Have got this working locally, and added the UVs you mentioned were missing on some. 
Just want to switch it over to using the gradient map rather than the ramp and I'll commit it.

**Comment by Holopointz** [comment]
Yesss! Awesome, thank you Sim! Looking forward to it:)

**Comment by Simarilius-uk** [comment]
duplicates and UVs are in the current main

**Comment by Holopointz** [comment]
Thank you choom! Can't wait to try it!
