### ISSUE TITLE
Feature Request: Transform

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#28]
Right now, transformations (deltas) will be ignored. In the original plugin, there is an "apply transformations" checkbox, but the Cyberpunk plugin doesn't offer that option.

Instead of simply offering the option without explanation, it would be great to make that a little more ~~idiot~~user friendly: I had to learn the hard way that you need to "Apply All Transforms" by hand and it cost me several hours where I didn't understand why my prop wasn't scaling because IT LOOKED OKAY IN BLENDER!!! 

Potential options: 

## Checkbox in the settings
Setting either of these could disable the check/prompt in the next section
- Always include transforms
- Always ignore transforms
... and will be mutually exclusive

## Prompt
"You have transformations that you haven't applied yet. Do you want to include them in your export?"
- Yes: Will set "include transforms" flag of export
- No: Will export as-it-is

**Comment by DoctorPresto** [comment]
The only issue with this is that the setting that applies the transforms at export, also prevents shapekeys from being exported. I'll have to take a closer look at some workarounds that don't nuke shapekeys. Shouldn't be too difficult to implement

**Comment by DoctorPresto** [comment]
submitted a PR to complete this :D
