### ISSUE TITLE
Ability to have groups of meshes in entities when importing a sector

### ISSUE THREAD

**Issue by Ametis81** [WolvenKit/Cyberpunk-Blender-add-on#31]
When importing a sector in Blender, we got ent_group_bla_bla_bla name with a bunch of meshes inside that group.

Is it possible to save groups of meshes like when we are importing a separate ent.json file?

Currently we have:

interior_a_b_c_d.streamingsector
|-ent_group_bla_bla_bla
 |-submesh_00_LOD_1.000
 |-submesh_00_LOD_1.001
 |-submesh_00_LOD_1.002
 |-submesh_01_LOD_1.000 ...

Here it's what it should be:

interior_a_b_c_d.streamingsector
|-ent_group_bla_bla_bla
 |-ent_subgroup1_bla_bla_bla 
  |-submesh_00_LOD_1.000
  |-submesh_01_LOD_1.000
 |-ent_subgroup2_bla_bla_bla
  |-submesh_00_LOD_1.001
  |-submesh_01_LOD_1.001 ...

**Comment by Simarilius-uk** [comment]
Should be fixed in main
