### ISSUE TITLE
Documentation Issue: Missing Entity Import wscript & linking to discord

### ISSUE THREAD

**Issue by thunderysteak** [WolvenKit/Cyberpunk-Blender-add-on#45]
This [following section in the documentation](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/blob/main/README.md#streaming-sector-import) mentions a wscript to automate the streaming sector mesh export, but it just points the user to go to a discord channel to find it.

There are several issues regarding this:

1. A user that is not already knee deep in trying to figure out WolvenKit won't know WHICH discord
2. There's no such `#wolvenkit-scripts` channel in the Cyberpunk 2077 Modding Community Discord that can be found through WolvenKit sites, neither it is in the archived channels
3. Nothing in pinned in related discord channels or the Blender channel
4. Searching in the discord doesn't yield any results

Please don't gate downloads behind a discord server, it's heavily susceptible to content drift, cannot be contributed to, and can't even be archived.

**Comment by dragonzkiller** [comment]
Please read the channel list again, as that channel does exist. Issue is closed.

**Comment by thunderysteak** [comment]
@dragonzkiller As shown on Discord that channel doesn't show up if you select "Show me everything" and had to be linked to it
![Discord_2023-09-14_23-42-11](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/16468437/0f8a24b3-492d-47f4-94cd-01a20fd51cdb)

And from there I found out that the script is not there, and it's in the latest nighty of WolvenKit, making the whole "Join this discord" dance redundant

Happy to submit a PR to correct the doc to reflect that
