### ISSUE TITLE
glb import issue

### ISSUE THREAD

**Issue by aNOniME01** [WolvenKit/Cyberpunk-Blender-add-on#49]
I'm having a problem when importing a mesh, I get an error message that says:

 

> Python: Traceback (most recent call last):
  File "C:\Users\<BlenderLoc>\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\__init__.py", line 358, in execute
    bpymat = Builder.create(index)
  File "C:\Users\<BlenderLoc>\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\main\setup.py", line 48, in create
    multilayered.create(rawMat["Data"],bpyMat)
  File "C:\Users\<BlenderLoc>\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 334, in create
    MBI = imageFromPath(self.BasePath+Microblend,self.image_format,True)
TypeError: can only concatenate str (not "dict") to str

The mesh itself imports correctly, but it's not applying any materials or textures. I've tried this with different meshes, and it works fine for things like transparent stickers and character skins. However, it's not working as expected for cyberwear and other objects.

I tried it with multiple blender and Wolvenkit versions but none seemed to solve the problem (B3.6.2 | B3.6 | WK10 | WK11).
I have also left every setting on default in both Wolvenkit and Blender.

I'm not sure if I'm doing something wrong during the import process or if there's a software issue. I've followed all the instructions in the presentation, and I haven't seen anyone else with this problem.

**Comment by DoctorPresto** [comment]
Make sure you're using the release candidate version. The error indicates there are old files in your material depot, best thing is to just delete the folder and re export whatever meshes you're trying to use

**Comment by aNOniME01** [comment]
I've tested it with the release candidate (1.4) using a freshly exported folder named "v_sportbike1_yaiba_kusanagi" in WKNightly 8.11 and CP2077 2.1 installed and I was using Blender 3.6.2. However, I encountered the following error message:
> Python: Traceback (most recent call last):
  File "C:\Users\<BlenderLoc>\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\__init__.py", line 339, in execute
    Builder = MaterialBuilder(obj,DepotPath,str(self.image_format),BasePath)
TypeError: MaterialBuilder.__init__() takes 4 positional arguments but 5 were given

Additionally, the model still doesn't have any materials attached. The mesh I attempted to import is named "v_sportbike1_yaiba_kusanagi__ext01_body_01.glb," but I encountered the same error when importing different parts as well.

**Comment by DoctorPresto** [comment]
The material depot is separate from your project. In wolvenkit check in tools-settings for the Depot, delete that folder and re export

**Comment by aNOniME01** [comment]
Thank you, this fixed the issue.
