### ISSUE TITLE
ent materials import issue

### ISSUE THREAD

**Issue by BrandonF111** [WolvenKit/Cyberpunk-Blender-add-on#54]
Software: Blender 3.6
Add-on: Version 1.4.0 RC 1
Issue: Getting a TypeError issue on some materials when importing a character ent file. Not sure if the issue is only with ep1 models, but I got the issue when importing president Myers, Angie, and Songbird. I checked the discord for any solutions, but I thought I would ask here. 
![blender issue 1](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/99161070/22d0ffdd-790c-42bb-b90e-81dfea6bb50b)

**Comment by DoctorPresto** [comment]
Can you try changing the depot and re exporting? Go to preferences in wolvenkit and add a 1 or _test to the folder name that's there and then re export all the meshes and try reimporting the ent

**Comment by BrandonF111** [comment]
Will try that now

**Comment by BrandonF111** [comment]
That seemed to work, thank you. Is there any specific reason as to why that fixed it?

**Comment by DoctorPresto** [comment]
There was a change to the way materials are output quite a while ago now, there error was because there are some old.jsons in your depot. Best solution is to just delete the old depot folder and carry on using the new one

**Comment by BrandonF111** [comment]
Will do. Thanks again for the help
