### ISSUE TITLE
Normal map issues

### ISSUE THREAD

**Issue by Scamarai** [WolvenKit/Cyberpunk-Blender-add-on#59]
Idk if this is just something on my end or if I'm even posting on the right github page, but I've found that recently normal maps (for layers as far as I'm aware atm) don't have their green channels inverted. It seems to be most noticeable on anything that uses leather materials. Say loudspeakers or the inside of a car (I'm currently using the villefort cortes). I don't paticuarly wanna go through hundreds of layers just to invert green channels properly. 
Not sure if its just my end/doing or if its incorrect for other people too.

**Comment by Simarilius-uk** [comment]
is this on multlayer stuff?

**Comment by Scamarai** [comment]
aye, that it is.

**Comment by DoctorPresto** [comment]
Can you confirm what plugin version, Wolvenkit version and blender version?

**Comment by Scamarai** [comment]
Addon says 1.5 , wolvenkit says 8.11.0 in the corner and blender is 3.6.5

**Comment by Simarilius-uk** [comment]
pretty sure Jato pushed a fix for this to git last night

**Comment by Scamarai** [comment]
assuming thats different from a release since the last release was 3 days ago. I'm not much of a github user so I assume it would be like a next update sorta thing?

**Comment by Simarilius-uk** [comment]
yeah, but you can just download https://github.com/WolvenKit/Cyberpunk-Blender-add-on/blob/main/i_scene_cp77_gltf/material_types/multilayered.py 
and replace the one in your plugin with it if you want to test it. If you enter %appdata% in the path bit of an explorer window the plugin will be in Blender\3.6\scripts\addons  (under the version of blender your using)

**Comment by Scamarai** [comment]
oh that works wonders. 'Preciate it yall 👍
