### ISSUE TITLE
[Suggestion] Preparation for Blender 4.0

### ISSUE THREAD

**Issue by Surasia** [WolvenKit/Cyberpunk-Blender-add-on#61]
Blender 4.0 changes the Principled BSDF node to the new v2 version of it, which'll require reworking all the material types. I'm going to try making a PR for the repo to edit some of the material type definitions, however the new Blender shader brings with it core rendering changes to it too, so maybe a github discussion on this repo to cover the topic would be of best use. 

4.0 Blender API: https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API

**Comment by Simarilius-uk** [comment]
I've already updated most of it for 4.0, just need to test it.
https://github.com/WolvenKit/Cyberpunk-Blender-add-on/tree/Blender4Compat

**Comment by Surasia** [comment]
Oh, for some reason it didn't pop up on the tree list, thanks!
