### ISSUE TITLE
Sector import: Consider ep1/ part of sector name for export script

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#62]
Some sector names are not unique (because why would they be?) Instead, they're unique by file path, for example those bad beans:
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/965785/411e82c5-07dd-4ef9-a06e-508874a3b3eb)

If the sector import plugin could keep the `ep1/` part of the path in front of the sector file name, then the export script would Just Work:tm: :)

**Comment by Simarilius-uk** [comment]
is this for the plugin or the wscript?

**Comment by manavortex** [comment]
For the plugin, since it'll need to change the name of the collections in Blender

**Comment by manavortex** [comment]
I can use the sector's filepath property to get the correct file name, so this isn't needed anymore :3
