### ISSUE TITLE
Sector import: numMeshChildren/numArmatureChildren

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#64]
It would be great if collections could be given two additional properties on import: 

### numMeshChildren
How many meshes are in this collection? That way, we could set up a threshold in the export deletion script, e.g. "treat everything with one deleted submesh as a deletion"

### numArmatureChildren
How many armature children are in this collection? That way, we could have a flag for the export to ignore armature deletions.

**Comment by Simarilius-uk** [comment]
in commit b92906a in the Blender4Compat branch
