### ISSUE TITLE
parallaxscreen not compatible with Blender 4.0

### ISSUE THREAD

**Issue by Surasia** [WolvenKit/Cyberpunk-Blender-add-on#70]
Any materials using the parallaxscreen mt will not import properly, with this error:

```
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\i_scene_cp77_gltf\importers
\import_with_materials.py", line 148, in CP77GLBimport
    bpymat = Builder.create(index)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\i_scene_cp77_gltf\main\setup.py", line 168, in create
    meshDecalParallax.create(rawMat["Data"],bpyMat)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\i_scene_cp77_gltf\material_types\parallaxscreen.py", line 214, in create
    scroll1Group.inputs.new('NodeSocketFloat','ScrollSpeed1')
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'

```

**Comment by Simarilius-uk** [comment]
bugger. missed one. Thanks for the report.

**Comment by Surasia** [comment]
meshdecalparallax seems to have a similar issue too. Can't get the traceback right now, but it was the same ScrollSpeed input.

**Comment by Simarilius-uk** [comment]
yeah, the tv ad one as well, looking at them now

**Comment by Simarilius-uk** [comment]
Would help if they'd actually documented all the things they'd changed

**Comment by Simarilius-uk** [comment]
https://github.com/WolvenKit/Cyberpunk-Blender-add-on/pull/72 has the parallax screen working, will look at the others tomorrow

**Comment by Simarilius-uk** [comment]
> meshdecalparallax seems to have a similar issue too. Can't get the traceback right now, but it was the same ScrollSpeed input.

you sure its not the same error? The parallax screen was using a setup called meshdecalparallax by mistake, so thats in the error you posted too

**Comment by Surasia** [comment]
Ah yep, same error. Sorry for the confusion. Also FYI, you can use something like NodeTree source to automatically turn the nodes into scripts without typing them out. Produces a very large file, but it can be cut down using some simple regex.

**Comment by Simarilius-uk** [comment]
Yeah, I have used that for some stuff, like the interior mapped room tree, but its not updated to B4 yet as far as I know, and so if we want B3 & B4 theres still a fair bit of manual tweaking required. Thanks for the tip tho :)
Shot fixed the tv one while I was asleep, so both are fixed in main.
