### ISSUE TITLE
Collision Mesh Actors

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/Cyberpunk-Blender-add-on#76]
Seb is enabling the meshes to be exported from the collision cache thing to json, need to implement import and add to the sectors import.
Have some initial code to bring in and convert to a mesh.

**Comment by DoctorPresto** [comment]
Drawing the meshes should be a simple addition, should be able to add this over the weekend.

Do we want the ability to write these out as well? 

S

**Comment by Simarilius-uk** [comment]
Dont think we can import, so no point in exporting currently. I've got the code for import done already.

**Comment by Simarilius-uk** [comment]
theres code in https://github.com/WolvenKit/Cyberpunk-Blender-add-on/blob/main/i_scene_cp77_gltf/importers/collision_mesh_import.py that imports them if called, I just havent hooked it into anything yet

**Comment by Simarilius-uk** [comment]
have these being imported by the sector import now. Is in my github, will be in my next big commit.
