### ISSUE TITLE
Iteration go brr when transfering vertex weights with different mesh numbers

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#79]
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/965785/d7960507-45bd-4127-9fd0-00d0322edc2c)

When transferring vertex weights between collections, there'll be an exception unless both collections have the same number of submeshes.

**Comment by DoctorPresto** [comment]
On it!
