### ISSUE TITLE
Error when installing addon to Blender ver.4.0.1

### ISSUE THREAD

**Issue by Rudolph2109** [WolvenKit/Cyberpunk-Blender-add-on#80]
![Blender Error](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/113218540/69bf8c19-0087-4820-bbe4-6f6b87827324)

When attempting to activate the addon in Blender after installing it, I am getting this error shown in the image.

**Comment by DoctorPresto** [comment]
What plugin version?

**Comment by DoctorPresto** [comment]
Looks like an error from an improperly packed version. Grab 1.5.1 https://github.com/WolvenKit/Cyberpunk-Blender-add-on/releases/tag/v1.5.1

**Comment by DoctorPresto** [comment]
100%. I'm guessing they found 1.5.1 and forgot about this ticket by now too :D
