### ISSUE TITLE
The problem of importing to Blender 3.6

### ISSUE THREAD

**Issue by sibawal** [WolvenKit/Cyberpunk-Blender-add-on#85]
Good afternoon. When I stream import through the plugin, the interior is not going to be assembled, all the meshes are collected at a central point in one pile, the plugin and the Top of the latest version. Blender 3,6!
![Снимок экрана 2023-11-26 221244](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/52999882/f00a7db8-fc18-42f6-a2f6-340a572c0f53)

**Comment by Simarilius-uk** [comment]
those are your masterinstances probably, were they hidden when it finished importing? 
in your tree there should be a collector with the sector name, click on one of the objects and press keypad .

**Comment by sibawal** [comment]
![Снимок экрана 2023-11-27 114039](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/52999882/4fde1d16-3c88-4cab-b873-99c17cb674b6)
No, I only load meshes. There is not one with the name of the sector.
![Снимок экрана 2023-11-27 113910](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/52999882/c7f322fe-f183-4384-974e-14648e8b8ecb)
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/52999882/93a03e2a-e144-42be-9219-22c3039de6ba)
It doesn't take long for the light to appear.

**Comment by DoctorPresto** [comment]
That is the master instances collection like sim suggested. Hide and collapse it from the outliner view and you'll see the other. ![285732117-c7f322fe-f183-4384-974e-14648e8b8ecb~2.png](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/111536029/29ed6fe9-3a4e-462a-bbbe-2e2e2f69090c)
